

spring:
  redis:
    host: ---your url---
    port: ---port--- // 6397
  # jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  # datasource configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/---your database---?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username:  xxx
    password:  xxx
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss.SSS
  data:
    mongodb:
      uri: mongodb://---your database---/articles
  rabbitmq:
    host: ---url---
    port: 5672
    username: ---your user---
    password: ---your password---
  stomp:
    port: 61613
  mail:
    host: ---your email---
    port: ---your port---
    username: ---your email address---
    password: ---your email Auther key---    # 授权码
    default: UTF-8
    socketFactoryClass: javax.net.ssl.SSLSocketFactory   # 加密工厂
    debug: true
    from: ---your email address---
    protocol: smtp     #使用的协议
    smtp:
      ssl:
        enable: true    # 是否开启 ssl 认证协议
      socketFactory:
        port: 587       #使用默认接口即可
      auth: true
      starttls:
        enable: true
        required: true



logging:
  file:
    path: /var/log
    file: Hi.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG



