

spring:
  redis:
    host: localhost
    port: 6379
  # jpa configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  # datasource configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentsource?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss.SSS
  data:
    mongodb:
      uri: mongodb://localhost:27017/articles
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  stomp:
    port: 61613
  mail:
    host: smtp.qq.com
    port: 587
    username: 3312988295@qq.com
    password: cfzpmwstjhxbchdf    # 授权码
    default: UTF-8
    socketFactoryClass: javax.net.ssl.SSLSocketFactory   # 加密工厂
    debug: true
    from: 3312988295@qq.com
    protocol: smtp     #使用的协议
    smtp:
      ssl:
        enable: true    # 是否开启 ssl 认证协议
      socketFactory:
        port: 587       #使用默认接口即可
      auth: true
      starttls:
        enable: true
        required: true



logging:
  file:
    path: /var/log
    file: Hi.log
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

jwt:
  secret: "2133344126997718w2anderer52334428577419an1tsu21777216b1s2t"
  #弃用


